#!/usr/bin/env bash

# install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

mkdir -p ~/.gnupg; ln -sf ~/.dotfiles/gpg-agent.conf ~/.gnupg
ln -sf ~/.dotfiles/.zshrc ~
ln -sf ~/.dotfiles/.vimrc ~
ln -sf ~/.dotfiles/.gitconfig ~
ln -sf ~/.dotfiles/.gitexclude ~

# zinit
bash -c "$(curl --fail --show-error --silent --location https://raw.githubusercontent.com/zdharma-continuum/zinit/HEAD/scripts/install.sh)"

# Optional dotfiles
cp ~/.dotfiles/.gitconfig.local ~

# neovim
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
ln -sf ~/.dotfiles/init.vim ~/.config/nvim/init.vim

# claude-code
curl -fsSL https://claude.ai/install.sh | bash

mkdir -p ~/.tweakcc && ln -s ~/.dotfiles/.tweakcc/config.json ~/.tweakcc/config.json
# pnpx tweakcc --apply

# Disable Last login message
touch ~/.hushlogin
