#!/usr/bin/env bash
source ~/.dotfiles/macOS/system.bash

touch ~/.huslogin

source ~/.dotfiles/macOS/brew.bash
source ~/.dotfiles/macOS/apps/iterm.bash

source ./vscode/init

cd ~/.dotfiles/macOS/wallpaper && pipenv install && crontab crontab -u

sudo shutdown -r now
