#!/usr/bin/env bash
source ~/.dotfiles/macOS/system.bash

touch ~/.huslogin

source ~/.dotfiles/macOS/brew.bash
source ~/.dotfiles/macOS/apps/iterm.bash
source ~/.dotfiles/macOS/apps/lauch-agents.bash

source ./vscode/init

crontab ~/.dotfiles/macOS/wallpaper/crontab -u

sudo shutdown -r now
